---
- name: Kubernetes master installation
  hosts: all # value here is important!
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: hostnamectl set-hostname 'k8s-master'
      shell: hostnamectl set-hostname 'k8s-master'

    - name: exec bash
      shell: exec bash

    - name: setenforce 0
      shell: setenforce 0

    - name: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux
      shell: sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux

    - name: firewall-cmd --permanent --add-port=6443/tcp
      shell: firewall-cmd --permanent --add-port=6443/tcp

    - name: firewall-cmd --permanent --add-port=2379-2380/tcp
      shell: firewall-cmd --permanent --add-port=2379-2380/tcp

    - name: firewall-cmd --permanent --add-port=10250/tcp
      shell: firewall-cmd --permanent --add-port=10250/tcp

    - name: firewall-cmd --permanent --add-port=10251/tcp
      shell: firewall-cmd --permanent --add-port=10251/tcp

    - name: firewall-cmd --permanent --add-port=10252/tcp
      shell: firewall-cmd --permanent --add-port=10252/tcp

    - name: firewall-cmd --permanent --add-port=10255/tcp
      shell: firewall-cmd --permanent --add-port=10255/tcp

    - name: firewall-cmd --reload
      shell: firewall-cmd --reload

    - name: modprobe br_netfilter
      shell: modprobe br_netfilter

    - name: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
      shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables

    - name: src=add-k8s-to-yum.sh dest=/home/Rieh mode=0777
      copy: src=add-k8s-to-yum.sh dest=/home/Rieh mode=0777

    - name: sh /home/Rieh/add-k8s-to-yum.sh
      command: sh /home/Rieh/add-k8s-to-yum.sh

    - name: yum install docker -y
      shell: yum install docker -y

    - name: systemctl restart docker
      shell: systemctl restart docker

    - name: systemctl enable docker
      shell: systemctl enable docker

    # - name: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    #   shell: yum install -y kubelet kubeadm kubectl --disableexcludes=kubernetes

    - name: yum install kubeadm -y
      shell: yum install kubeadm -y

    - name: systemctl restart kubeadm
      shell: systemctl restart kubeadm

    - name: systemctl enable kubeadm
      shell: systemctl enable kubeadm

    - name: yum install kubectl -y
      shell: yum install kubectl -y

    - name: systemctl restart kubectl
      shell: systemctl restart kubectl

    - name: systemctl enable kubectl
      shell: systemctl enable kubectl

    - name: yum install kubelet -y
      shell: yum install kubelet -y

    - name: systemctl restart kubelet
      shell: systemctl restart kubelet

    - name: systemctl enable kubelet
      shell: systemctl enable kubelet

    - name: EX
      shell: kubeadm init

    - name: EX
      shell: mkdir -p $HOME/.kube

    - name: EX
      shell: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

    - name: EX
      shell: chown $(id -u):$(id -g) $HOME/.kube/config

    - name: EX
      shell: export kubever=$(kubectl version | base64 | tr -d '\n')

    - name: EX
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"

    - name: EX
      shell: kubectl get nodes

    - name: EX
      shell: kubectl get pods --all-namespaces