---
- name: Jenkins master installation
  hosts: all # value here is important!
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: EX
      shell: kubectl apply -f deployment.yaml

    - name: EX
      shell: kubectl create -f service.yaml

    - name: EX
      shell: kubectl get service # Get the port of Jenkins master

    - name: EX
      shell: kubectl cluster-info | grep master

    - name: EX
      shell: kubectl get pods | grep jenkins